### ISSUE TITLE
Pure shadow-cljs / npm without CLJSJS?

### ISSUE THREAD

**Issue by rberger** [arttuka/reagent-material-ui#2]
This looks like an exciting project. But I don't understand what's up with the requirement for `thheller/shadow-cljsjs` and the wrapper in `/example/src/shadow-cljs/example/main.cljs`.

My project already includes react and react-dom via shadow-cljs / npm. Is the cljsjs stuff the only way to make it work? 

Thanks!

**Comment by manuel-uberti** [comment]
Any news on this? :)

**Comment by arttuka** [comment]
Sorry for the slow response, I haven’t had any time for this in the past months. 

I had the assumption that Reagent and other libraries relied on the cljsjs React package. Now that I researched further, I was incorrect and this issue has been fixed in reagent-material-ui version 4.11.0-1. The example project has also been updated.
