### ISSUE TITLE
Defective behavior of `date-picker` when deleting

### ISSUE THREAD

**Issue by egg-juxt** [arttuka/reagent-material-ui#39]
I am experiencing some unexpected cursor jumps when deleting a `date-picker` using the backspace key. This happens when `date-picker` is created with the property:
```
                 :render-input (react-component [props]
                                 [text-field props])
```
as in [this example](https://github.com/arttuka/reagent-material-ui/blob/master/example/src/example/core.cljs#L153).

The cursor behaves correctly with the property:
```
       :renderInput (fn [params]
                      (r/as-element
                        [mui/text-field (js->clj params)]))
```

Why is this?

**Comment by arttuka** [comment]
Looks like `DatePicker` is setting the cursor position when you type in the text field. If it is a Reagent input, Reagent also tries to set the cursor position which causes the cursor to jump unexpectedly. 

The solution is to render a React input instead of a Reagent input:
```clojure
(:require [react :as react]
          ["@mui/material/TextField" :as MuiTextField])

:render-input (fn [params] (react/createElement MuiTextField/default params))
```

Using `js->clj` fixed the issue by accident. It caused invalid props to be passed to `mui/text-field` so a default input was rendered instead of the custom Reagent input.
